# Site settings
title: Musings of Andrew Dane
description: > # this means to ignore newlines until "baseurl:"
 Spent a year managing junk food. Garnered an industry award while selling food in concerts and music festivals. Spent the 80's analyzing electric planes for farmers. Had some great experience testing the market for food delivery. Spent 2002-2009 consulting about plabes in Suffolk, NY. A real dynamo when it comes to lecturing about food delivery and planes.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

theme: jekyll-theme-dinky
